apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-present
  labels:
    app: k8s-present
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-present
  template:
    metadata:
      labels:
        app: k8s-present
    spec:
      containers:
      - name: k8s-present
        image: jupiter.local:5000/k8s-present:0.0.2
        ports:
        - containerPort: 3999
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-present-service
spec:
  selector:
    app: k8s-present
  ports:
    - port: 3999
      targetPort: 3999
  type: LoadBalancer